[package]
name = "ttt-rs"
version = "0.1.0"
authors = ["K3cs1 <kecskemetip@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.2"
log = "0.4.21"
petgraph = "0.6.4"
petgraph-evcxr = "0.2.0"
rand = "0.8.5"
slint = "1.5"

[build-dependencies]
slint-build = "1.5"
